version: '3.8'

services:
  sypnex-os:
    build: .
    container_name: sypnex-os
    ports:
      - "5000:5000"
    volumes:
      # Mount the data directory to persist databases and user data
      - sypnex-data:/app/data
      # Optional: Mount for development (uncomment for development)
      # - .:/app
      # - /app/__pycache__
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  # Named volume for persistent data storage
  sypnex-data:
    driver: local
