version: '3.8'

services:
  sypnex-os:
    build: .
    container_name: sypnex-os
    ports:
      - "5000:5000"
    volumes:
      # Mount the data directory to persist databases and user data
      - sypnex-data:/app/data
      # Optional: Mount for development (uncomment for development)
      # - .:/app
      # - /app/__pycache__
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PYTHONPATH=/app
      # Authentication users (username:bcrypt_hashed_password)
      # Demo user with password: demo123
      - AUTH_USER_1=demo:$$2b$$12$$fmHQckTV.N5z9sFT/4.kM.M24aqSJIqbUAKBcJwJHGoNP9nr32gJC
      - INSTANCE_NAME=docker-demo-instance
      - SESSION_SECRET_KEY=docker-super-secret-session-key-change-me
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  # Named volume for persistent data storage
  sypnex-data:
    driver: local
