# .github/workflows/release.yml

name: Create GitHub Release (Simplified)

on:
  push:
    branches:
      - master # Trigger on pushes to the 'master' branch
  workflow_dispatch: # This line allows you to manually trigger the workflow from the GitHub UI

jobs:
  release-specific-file:
    runs-on: ubuntu-latest # Use a Linux runner
    permissions:
      # Grant write permission to the GITHUB_TOKEN for contents (required for releases)
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: List root directory contents (Enhanced Diagnostic)
        run: |
          echo "Contents of the repository root directory:"
          ls -la .
          echo "--- End of root directory contents ---"

      - name: List files in examples directory (Enhanced Diagnostic)
        run: |
          echo "Contents of the 'examples' directory:"
          # Use 'find' to show files and their full paths, including case sensitivity
          find examples/ -maxdepth 1 -print -ls
          echo "--- End of 'examples' directory contents ---"

      - name: Verify specific file existence (Enhanced Diagnostic)
        run: |
          if [ -f "examples/flow_editor_packaged.app" ]; then
            echo "✅ File 'examples/flow_editor_packaged.app' found!"
            ls -la examples/flow_editor_packaged.app
          else
            echo "❌ File 'examples/flow_editor_packaged.app' NOT found at expected path."
            echo "Please check path, filename (including case), and if it's committed."
          fi

      - name: Create GitHub Release and Upload Specific Asset
        id: create_release
        uses: softprops/action-gh-release@v2 # Action to create a GitHub Release
        with:
          # Use the GITHUB_RUN_NUMBER for a unique release name.
          # This will be like "Release 1", "Release 2", etc.
          name: Release ${{ github.run_number }}
          tag_name: release-${{ github.run_number }} # A unique tag is still required by GitHub,
                                                      # so we'll auto-generate one based on run number.
          body: |
            ## Automated Release #${{ github.run_number }}

            This release includes the `flow_editor_packaged.app` file.
            Triggered by a push to the `master` branch.

            ### File Included:
            - `/examples/flow_editor_packaged.app`
          draft: false
          prerelease: false
          # Specify the exact path to your .app file relative to the repository root
          files: |
            examples/flow_editor_packaged.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions
