# .github/workflows/release.yml

name: Create GitHub Release (Simplified)

on:
  push:
    branches:
      - master # Trigger on pushes to the 'main' branch (or 'master' if you use that)
  workflow_dispatch: # This line allows you to manually trigger the workflow from the GitHub UI

jobs:
  release-specific-file:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Create GitHub Release and Upload Specific Asset
        id: create_release
        uses: softprops/action-gh-release@v2 # Action to create a GitHub Release
        with:
          # Use the GITHUB_RUN_NUMBER for a unique release name.
          # This will be like "Release 1", "Release 2", etc.
          name: Release ${{ github.run_number }}
          tag_name: release-${{ github.run_number }} # A unique tag is still required by GitHub,
                                                      # so we'll auto-generate one based on run number.
          body: |
            ## Automated Release #${{ github.run_number }}

            This release includes the `flow_editor_packages.app` file.
            Triggered by a push to the `main` branch.

            ### File Included:
            - `/examples/flow_editor_packages.app`
          draft: false
          prerelease: false
          # Specify the exact path to your .app file relative to the repository root
          files: |
            releases/flow_editor_packages.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions
