# .github/workflows/release.yml

name: Create GitHub Release (Simplified)

on:
  push:
    branches:
      - master # Trigger on pushes to the 'master' branch
  workflow_dispatch: # This line allows you to manually trigger the workflow from the GitHub UI

jobs:
  release-specific-file:
    runs-on: ubuntu-latest # Use a Linux runner
    permissions:
      # Grant write permission to the GITHUB_TOKEN for contents (required for releases)
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: List root directory contents (Diagnostic)
        run: |
          echo "Contents of the repository root directory:"
          ls -la .
          echo "--- End of root directory contents ---"

      - name: List files in examples directory (Diagnostic)
        run: |
          echo "Contents of the 'examples' directory:"
          find examples/ -maxdepth 1 -print -ls
          echo "--- End of 'examples' directory contents ---"

      - name: Verify specific file existence (Diagnostic)
        run: |
          # Corrected filename here
          if [ -f "examples/flow_editor_packaged.app" ]; then
            echo "✅ File 'examples/flow_editor_packaged.app' found!"
            ls -la examples/flow_editor_packaged.app
          else
            echo "❌ File 'examples/flow_editor_packaged.app' NOT found at expected path."
            echo "Please check path, filename (including case), and if it's committed."
            exit 1 # Exit if file not found, to prevent release creation with missing asset
          fi

      - name: Copy .app file and rename for release upload (Workaround for .app extension issue)
        run: |
          # Corrected source filename, and renaming to .bin for upload
          cp examples/flow_editor_packaged.app flow_editor_packaged.bin
          echo "Copied flow_editor_packaged.app to flow_editor_packaged.bin for upload."
          ls -la flow_editor_packaged.bin # Verify copy and new name

      - name: Create GitHub Release and Upload Specific Asset
        id: create_release
        uses: softprops/action-gh-release@v2 # Action to create a GitHub Release
        with:
          name: Release ${{ github.run_number }}
          tag_name: release-${{ github.run_number }}
          body: |
            ## Automated Release #${{ github.run_number }}

            This release includes the `flow_editor_packaged.app` file.
            Triggered by a push to the `master` branch.

            ### File Included:
            - `/examples/flow_editor_packaged.app` (Original Path)

            **Important:** The attached file is named `flow_editor_packaged.bin`.
            Please rename it to `flow_editor_packaged.app` after downloading.
          draft: false
          prerelease: false
          # Now point to the renamed .bin file in the root directory
          files: |
            flow_editor_packaged.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
